version: '3.8'

services:

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: impactin-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: impactin_user
      PMA_PASSWORD: impactin_pass
    ports:
      - "8081:80"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - impactin-network

  mysql:
    image: mysql:8.0
    container_name: impactin-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: impactin_db
      MYSQL_USER: impactin_user
      MYSQL_PASSWORD: impactin_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - impactin-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: impactin-backend
    environment:
      - DB_USER=impactin_user
      - DB_PASSWORD=impactin_pass
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=impactin_db
      - RESET_DB=true
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - impactin-network



  frontend_admin:
    build:
      context: ./frontend-admin
      dockerfile: Dockerfile
    container_name: impactin-frontend-admin
    volumes:
      - ./frontend-admin/src:/app/src
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - impactin-network

  frontend_user:
    build:
      context: ./frontend-user
      dockerfile: Dockerfile
    container_name: impactin-frontend-user
    volumes:
      - ./frontend-user/src:/app/src
    ports:
      - "5174:5174"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - impactin-network


volumes:
  mysql_data:

networks:
  impactin-network:
    driver: bridge



